name: Push / pull-requests
on: [push, pull_request]

env:
  BUILD_TYPE: Release
  BUILD_FOLDER: ${{github.workspace}}/build
jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2

    - name: CMake configure
      run: cmake -DCMAKE_INSTALL_PREFIX=${{env.BUILD_FOLDER}} -DYASERIALIZER_BUILD_TESTS=ON -S ${{github.workspace}} -B ${{env.BUILD_FOLDER}}

    - name: CMake install
      run: cmake --build ${{env.BUILD_FOLDER}} --config ${{env.BUILD_TYPE}} --target install

    - name: CMake test
      working-directory: ${{env.BUILD_FOLDER}}
      run: ctest -C ${{env.BUILD_TYPE}} -T test --output-on-failure